!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitutils(f2pysetupfunc)
      use utils, only : openfile
      use utils, only : closefile
      use utils, only : getnblocks
      use utils, only : getgriddimension
      use utils, only : getblockinfo
      use utils, only : getbcinfo
      use utils, only : getbcdatasetinfo
      use utils, only : getbcdataarrayinfo
      use utils, only : getbcdataarray
      use utils, only : getb2binfo
      use utils, only : getconvinfo
      use utils, only : getconvarray
      use utils, only : getcoordinates
      use utils, only : writezone
      use utils, only : writecoordinates
      use utils, only : writebc
      use utils, only : writebcdataheader
      use utils, only : writebcdata
      use utils, only : writeb2b
      use utils, only : refine
      use utils, only : interpedge
      use utils, only : interpface
      use utils, only : computeconnectivity
      use utils, only : getnpatches
      use utils, only : getpatchinfo
      use utils, only : deallocpatches
      use utils, only : findbounds
      use utils, only : computevolumes
      use utils, only : calcgridratio
      use utils, only : convertplot3d
      external f2pysetupfunc
      call f2pysetupfunc(openfile,closefile,getnblocks,getgriddimension,&
     &getblockinfo,getbcinfo,getbcdatasetinfo,getbcdataarrayinfo,getbcda&
     &taarray,getb2binfo,getconvinfo,getconvarray,getcoordinates,writezo&
     &ne,writecoordinates,writebc,writebcdataheader,writebcdata,writeb2b&
     &,refine,interpedge,interpface,computeconnectivity,getnpatches,getp&
     &atchinfo,deallocpatches,findbounds,computevolumes,calcgridratio,co&
     &nvertplot3d)
      end subroutine f2pyinitutils


